// src/components/ContentDropdown.jsx
import "../styles/styles.css";
import { useState } from "react";
export let isOpen = false;

const ContentDropdown = (props) => {
    const [isOpen, setIsOpen] = useState(false);
    const handleClick = () => {
        setIsOpen(!isOpen);
    }
    return (
        <div>
            {
                <div>
                    <button className="flex" onClick={handleClick}>{props.item.title}
                        {isOpen ? <div className="rotate-90 px-4"><i className="fa-solid fa-chevron-right" /></div> : <div className="px-4"><i className="fa-solid fa-chevron-right" /></div>}
                    </button>
                    <p className={isOpen ? 'flex' : 'hidden'}>{props.item.content}</p>
                </div>
            }
        </div>
    )
};

export default ContentDropdown;

// src/components/ContentDropdown.svelte
<script>
    import "../styles/styles.css";
    export let label = "Dropdown";
    export let content =
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo, quisquam.";
    export let isOpen = false;
    export function handleClick() {
        alert("click!");
        isOpen = !isOpen;
    }
</script>

<div>
    <div onclick={handleClick} class="cursor-pointer">
        <button>{label}</button>
        <i
            class="fa-solid fa-chevron-right"
            data-fa-transform={isOpen ? "rotate-90" : ""}
        />
    </div>
    <div class={isOpen ? "flex" : "hidden"}>
        <p>{content}</p>
    </div>
</div>
